controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Appointment;
use app\models\Customer;
use app\models\Expend;
use app\models\File;
use app\models\FileStorageItem;
use app\models\Income;
use app\models\ListMeet;
use app\models\MeetingHasListMeet;
use app\models\Stock;
use yii\db\Exception;
use yii\db\Transaction;
use yii\helpers\ArrayHelper;
use app\models\Tr14;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    /*    public function actions()
        {
            return [
                'error' => [
                    'class' => 'yii\web\ErrorAction',
                ],
                'captcha' => [
                    'class' => 'yii\captcha\CaptchaAction',
                    'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                ],
            ];
        }*/
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function actionCalender()
    {
        /*$events = array();
        //Testing
        $appointment = Appointment::find()->all();
        $Event = new \yii2fullcalendar\models\Event();
        $Event->id = 1;
        $Event->title = 'Testing';
        $Event->start = date('Y-m-d\Th:m:s\Z');
        $events[] = $Event;

        $Event = new \yii2fullcalendar\models\Event();
        $Event->id = 2;
        $Event->title = 'Testing';
        $Event->start = date('Y-m-d\Th:m:s\Z',strtotime('tomorrow 6am'));
        $events[] = $Event;*/
        return $this->render('calender',[
           // 'events'=>$events
        ]);
    }
    public function actionJsoncalendar($start=NULL,$end=NULL,$_=NULL){
        $appointment = Appointment::find()->all();
        $events = array();

        foreach ($appointment AS $key =>$time){
            //Testing
            $Event = new \yii2fullcalendar\models\Event();
            $Event->id = $time->appoint_id;
            $Event->title = $time->appoint_name;
            $Event->start = date('Y-m-d\Th:m:s\Z',strtotime($time->appoint_date));
            //$Event->end = date('Y-m-d\Th:m:s\Z',strtotime($time->appoint_date));
            $Event->url = \Yii::getAlias('@web').'/appoint/'.$time->appoint_id;
            $Event->color = '#3960d1';
            $events[] = $Event;
        }

        header('Content-type: application/json');
        echo Json::encode($events);

        Yii::$app->end();
    }
    public function actionAjaxCalendar()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $start = \Yii::$app->request->post('start');
        $end = \Yii::$app->request->post('end');
          $activity = Appointment::find()->all();


        $data = [];
        foreach ($activity as $key => $item) {
            if (strtotime($item->date_start) != strtotime($item->date_end)) {
                $end = strtotime("+1 day", strtotime($item->date_end));
                $item->date_end = date("Y-m-d", $end);
            }
            if($item->approve == 1) $bgColor = '#2eb398';
            elseif($item->approve == 2) $bgColor = '#FF6C60';
            elseif($item->approve == 3) $bgColor = '#3f51b5';
            elseif($item->approve == 4) $bgColor = '#ebc142';

            $data[$key]['start'] = $item->date_start;
            $data[$key]['end'] = $item->date_end;
            $data[$key]['title'] = $item->activity_name_th;
            $data[$key]['color'] = $bgColor;
            $data[$key]['url'] = \Yii::getAlias('@web').'/activity-user/my-view?id='.$item->id;
        }
        return $data;
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        $user = Customer::find()->groupBy(['customer_id'])->count();

        $ym1 = Yii::$app->formatter->asDate('now', 'yyyy-MM');
        $ymd1 = $ym1."-1"; //เอาแต่วันที่ 1 ของเดือนนี้

        $currentDate = date('Y-m-d');
        $ymd2 = date("Y-m-t", strtotime($currentDate));


        $query = "SELECT
                    Count(meeting_has_list_meet.list_id) AS count,
                    list_meet.list_name
                    FROM
                    meeting_has_list_meet
                    INNER JOIN list_meet ON meeting_has_list_meet.list_id = list_meet.list_id
                    INNER JOIN meeting ON meeting_has_list_meet.meet_id = meeting.meet_id
                    WHERE
                    meeting.meet_date BETWEEN '".$ymd1."' AND '".$ymd2."'
                    GROUP BY
                    meeting_has_list_meet.list_id
                    LIMIT 5";

        $commandCountSt = Yii::$app->db->createCommand($query)->queryAll();
        $main_items = [];
        foreach ($commandCountSt AS $data) {
            $main_items[] = [
                'count' => $data['count'],
                'name' => $data['list_name'],
            ];
        }

        $stock = Stock::find()->where(['status'=>'1'])->all();
        $pill = [];

        if($stock){
            foreach ($stock AS $key=>$data) {
                if($data->left<=5){
                    $pill[$key]["name"] = $data->stock_name;
                    $pill[$key]["id"] = $data->stock_id;
                    $pill[$key]["left"] = $data->left;
                }
            }
        }
      /*  echo $main_items[0]['count'];
        exit();*/

        //Appointment
        $currentDate = date('Y-m-d');
        $appoint = Appointment::find()->filterWhere(['like', 'appoint_date', $currentDate])->andWhere(['status'=>'0'])->all();

        $income = Income::find()->where( ["between",".income_date", $ymd1, $ymd2] )->sum('income_number');
        $expend = Expend::find()->where( ["between",".expend_date", $ymd1, $ymd2] )->sum('expend_number');
     /*   var_dump($income);
        exit();*/

        if (Yii::$app->user->isGuest) {
            return Yii::$app->getResponse()->redirect(['user/login']);
        } else {
            // return Yii::$app->getResponse()->redirect( ['location/index'] );
            return $this->render('index', [
                'main_items' => $main_items ? $main_items : null,
                'customer'=> empty($user) ? 0 : $user,
                'pill'=>$pill?$pill:null,
                'appoint'=>$appoint?$appoint:null,
                'income'=>$income?$income:0,
                'expend'=>$expend?$expend:0,
            ]);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }
}

views/site/_excelForm.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\web\JsExpression;


?>
<br/><br/>
<?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-4">
            <?php Html::hiddenInput('txt_excel_path', '', ['class' => 'form-control', 'readonly' => true, 'id' => 'txt_excel_path']); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?php $form = ActiveForm::begin(['id'=>'import','options' => ['enctype'=>'multipart/form-data']]); ?>
            <?= $form->field($model,'file')->fileInput([])->label('Select File') ?>
        </div>
    </div>
    <hr>
    <div class="form-group">
        <?php echo Html::submitButton('<i class="fa fa-save"></i> บันทึก', ['class' => 'btn btn-success']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/calender.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 10/23/2018
 * Time: 10:36 PM
 */
?>
<div class="portlet">
    <div class="portlet-heading">
        <h3 class="portlet-title text-dark">
            Calender (ปฎิทิน)
        </h3>
        <div class="portlet-widgets">
        </div>
        <div class="clearfix"></div>
    </div>
    <div id="bg-default" class="panel-collapse collapse in">
        <div class="portlet-body">
            <?= yii2fullcalendar\yii2fullcalendar::widget(array(
                'options' => [
                    'lang' => 'th',
                ],
                'ajaxEvents' => \yii\helpers\Url::to(['/site/jsoncalendar'])
            ));
            ?>
        </div>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode('มีข้อผิดพลาด')) ?>
        <a  href="<?=\Yii::getAlias( '@web')?>/site/index" role="button">กลับไปยังหน้าหลัก</a><br/>
    </div>
    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/graph.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 7/7/2018
 * Time: 1:28 PM
 */
use miloschuman\highcharts\Highcharts;
$this->title = 'Graph';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="portlet">
    <div class="portlet-heading ">
        <h2 class="portlet-title text-dark">
            Graph
        </h2>
    </div>
    <div id="bg-primary" class="panel-collapse collapse in">
        <div class="portlet-body">
            <?php
            echo Highcharts::widget([
                'scripts' => [
                    'modules/exporting',
                    'themes/grid-light',
                ],

                'options' => [
                    'title' => [
                        // 'text' => 'กราฟแสดงรายการสูงสุด 5 อันดับแรก',
                    ],
                    'xAxis' => [
                        'classname'=>'highcharts-color-0',
                        'categories' => ['รายการ'],
                    ],
                    'credits' => ['enabled' => false],
//                            'colors'=> ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572',
//                                '#FF9655', '#FFF263', '#6AF9C4'],
                    'labels' => [
                        'items' => [
                            [
                                'style' => [
                                    'left' => '50px',
                                    'top' => '18px',
                                    'color' => new \yii\web\JsExpression('(Highcharts.theme && Highcharts.theme.textColor) || "black"'),
                                ],
                            ],
                        ],
                    ],
                    'series' => [

                        [
                            'type' => 'column',
                            'name' => empty($main_items[0]['name']) ? null : $main_items[0]['name'],
                            'data' => [ empty($main_items[0]['count']) ? null : (int)$main_items[0]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[1]['name']) ? null : $main_items[1]['name'],
                            'data' => [ empty($main_items[1]['count']) ? null : (int)$main_items[1]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[2]['name']) ? null : $main_items[2]['name'],
                            'data' => [ empty($main_items[2]['count']) ? null : (int)$main_items[2]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[3]['name']) ? null : $main_items[3]['name'],
                            'data' => [ empty($main_items[3]['count']) ? null : (int)$main_items[3]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[4]['name']) ? null : $main_items[4]['name'],
                            'data' => [ empty($main_items[4]['count']) ? null : (int)$main_items[4]['count'],],
                        ],



                    ],
                ]
            ]);
            ?>
        </div>
    </div>
</div>

views/site/index.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 7/7/2018
 * Time: 2:16 PM
 */
use miloschuman\highcharts\Highcharts;

?>
<div class="row">
    <div class="col-md-4">
        <div class="mini-stat clearfix">
            <span class="mini-stat-icon bg-pink"><i class="fa fa-user"></i></span>
            <div class="mini-stat-info text-right">
                <span class="counter"><?= $customer ?></span>
                Customer In System
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="mini-stat clearfix">
            <span class="mini-stat-icon bg-info"><i class="fas fa-dollar-sign"></i></span>
            <div class="mini-stat-info text-right">
                <span class="counter"><?=$income?></span>
                Total Income In Month
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="mini-stat clearfix">
            <span class="mini-stat-icon bg-warning"><i class="fa fa-shopping-cart"></i></span>
            <div class="mini-stat-info text-right">
                <span class="counter"><?=$expend?></span>
                Total Expenditure In Month
            </div>
        </div>
    </div>
</div>
<div class="portlet">
    <div class="portlet-heading ">
        <div class="pull-left">
            <h2 class="portlet-title text-dark">
                Notification
            </h2>
        </div>
        <div class="pull-right">
            <a href="<?=Yii::getAlias('@web/site/calender')?>" class="btn btn-pink btn-rounded m-b-5"><i class="fas fa-calendar-alt"></i> ปฎิทิน</a>
        </div>
<br/>
    </div>
    <div id="bg-primary" class="panel-collapse collapse in">
        <div class="portlet-body">
            <div class="row">

            <?php if($pill){
                foreach ($pill as $data){?>
                <div class="col-md-6">
                <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <span style="font-size:20px"> <i class="fas fa-pills"></i> </span>
                    <a href="<?= Yii::getAlias('@web/stock/update/').$data["id"] ?>" class="alert-link"> แจ้งเตือน <?= $data["name"] ?> เหลือ <?= $data["left"] ?></a>
                </div>
                </div>
            <?php }}?>


            <?php if($appoint){
                foreach ($appoint as $data){?>
            <div class="col-md-6">
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span style="font-size:20px;color: #b94a48"> <i class="far fa-comments"></i> </span>
                        <a href="<?= Yii::getAlias('@web/appoint/').$data["appoint_id"] ?>" class="alert-link">มีการนัดพบวันนี้เรื่อง <?=$data["appoint_name"]?> กับคุณ  <?=$data->customer->customer_name?> </a>
                    </div>
            </div>
                    <?php
                }
            }?>
                <?php if(!$appoint&&!$pill){ ?>
                    <div class="alert alert-info alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <span style="font-size:20px"> <i class="far fa-bell"></i> </span>
                        <a href="#" class="alert-link"> No Notification</a>
                    </div>
                <?php } ?>

            </div>
        </div>
    </div>
</div>
<div class="portlet">
    <div class="portlet-heading ">
        <h2 class="portlet-title text-dark">
            Graph
        </h2>
    </div>
    <div id="bg-primary" class="panel-collapse collapse in">
        <div class="portlet-body">
            <?php
            echo Highcharts::widget([
                'scripts' => [
                    'modules/exporting',
                    'themes/grid-light',
                ],

                'options' => [
                    'title' => [
                        // 'text' => 'กราฟแสดงรายการสูงสุด 5 อันดับแรก',
                    ],
                    'xAxis' => [
                        'classname' => 'highcharts-color-0',
                        'categories' => ['รายการ'],
                    ],
                    'credits' => ['enabled' => false],
//                            'colors'=> ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572',
//                                '#FF9655', '#FFF263', '#6AF9C4'],
                    'labels' => [
                        'items' => [
                            [
                                'style' => [
                                    'left' => '50px',
                                    'top' => '18px',
                                    'color' => new \yii\web\JsExpression('(Highcharts.theme && Highcharts.theme.textColor) || "black"'),
                                ],
                            ],
                        ],
                    ],
                    'series' => [

                        [
                            'type' => 'column',
                            'name' => empty($main_items[0]['name']) ? null : $main_items[0]['name'],
                            'data' => [empty($main_items[0]['count']) ? null : (int)$main_items[0]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[1]['name']) ? null : $main_items[1]['name'],
                            'data' => [empty($main_items[1]['count']) ? null : (int)$main_items[1]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[2]['name']) ? null : $main_items[2]['name'],
                            'data' => [empty($main_items[2]['count']) ? null : (int)$main_items[2]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[3]['name']) ? null : $main_items[3]['name'],
                            'data' => [empty($main_items[3]['count']) ? null : (int)$main_items[3]['count'],],
                        ],
                        [
                            'type' => 'column',
                            'name' => empty($main_items[4]['name']) ? null : $main_items[4]['name'],
                            'data' => [empty($main_items[4]['count']) ? null : (int)$main_items[4]['count'],],
                        ],


                    ],
                ]
            ]);
            ?>
        </div>
    </div>
</div>

views/site/index2.php
<?php

/* @var $this yii\web\View */

use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;
use yii\widgets\ActiveForm;

$this->title = 'Cher Charm Clinic';
?>

<div class="row">
    <div class="col-sm-4" align="left">
        <!--  <div class="panel bg-primary">
              <div class="panel-body">
                  <div class="h2 text-white m-t-10">956</div>
                  <p class="text-white m-b-10">New Customer</p>
              </div>
          </div>
        <!-- <div class="panel panel-default">
        <div class="panel-body">
            <h2> <i class="far fa-calendar-alt" style="font-size: 48px;"></i>
                &nbsp; <? /*= \app\controllers\GetpublicController::getDateThaiTime(date('Y-m-d')) */ ?></h2>
        </div>
    </div>-->
        <div class="list-group">
            <div class="list-group-item bg-primary">
                <div class="row">
                    <div class=" col-md-12" align="left">
                        <div style="font-size: 25px"><b><?= $customer ?></b></div>
                        <span style="font-size: 15px">Customer In System</span>
                    </div>
                </div>
            </div>
            <a href="<?= Yii::getAlias('@web') ?>/stock/index" class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
                        <span style="color:#007aff;font-size: 25px"><i class="fas fa-pills"></i></span>
                    </div>
                    <div class="col-xs-2 col-md-1" align="left">
                        <span style="font-size: 25px">Stock</span>
                    </div>
                </div>
            </a>
            <a href="<?= Yii::getAlias('@web') ?>/customer/index" class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
                        <span align="left" style="color:#007aff;font-size: 25px"><i class="fas fa-users"></i></span>
                    </div>
                    <div class="col-xs-2 col-md-1" align="left">
                        <span align="center" style="font-size: 25px">Customer</span>
                    </div>
                </div>
            </a>
            <a href="<?= Yii::getAlias('@web') ?>/appoint/index" class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
            <span style="color:#007aff;font-size: 25px">
                <i class="far fa-comments"></i></span>
                    </div>
                    <div class="col-xs-4 col-md-1" align="left">
                        <span style="font-size: 25px">Appointment</span>
                    </div>
                    <div class="col-xs-6 col-md-9" align="right">
                        <span class="label label-danger">2</span>
                    </div>
                </div>

            </a>
            <a href="<?= Yii::getAlias('@web') ?>/doctor/index" class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
            <span style="color:#007aff;font-size: 25px">
                <i class="fas fa-user-md"></i>
            </span>
                    </div>
                    <div class="col-xs-6 col-md-6" align="left">
                        <span style="font-size: 25px">Add Doctor</span>
                    </div>
                </div>
            </a>
            <a href="<?= Yii::getAlias('@web') ?>/users/approve" class="list-group-item">
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
            <span style="color:#007aff;font-size: 25px">
                <i class="fas fa-users-cog"></i>
            </span>
                    </div>
                    <div class="col-xs-6 col-md-6" align="left">
                        <span style="font-size: 25px">Approve User</span>
                    </div>
                </div>
            </a>
            <a class="list-group-item" data-toggle="modal" data-target="#myModal">
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
                        <span style="color:#007aff;font-size: 25px"><i class="far fa-file-alt"></i></span>
                    </div>
                    <div class="col-xs-2 col-md-1" align="left">
                        <span style="font-size: 25px">Report</span>
                    </div>
                </div>
            </a>
            <a href="<?= Yii::getAlias('@web') ?>/site/graph" class="list-group-item" >
                <div class="row">
                    <div class="col-xs-2 col-md-2" align="left">
            <span style="color:#007aff;font-size: 25px">
                <i class="fas fa-chart-line"></i>
            </span>
                    </div>
                    <div class="col-xs-2 col-md-1" align="left">
                        <span style="font-size: 25px">Graph</span>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-sm-8">


    </div>
</div>


<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <?php $form = ActiveForm::begin(['action' => 'graph/index', 'id' => 'report',]); ?>
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Report</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <label class="control-label" for="from">จาก</label>
                        <?= \dosamigos\datepicker\DatePicker::widget([
                            'name' => 'from',
                            'id' => 'from',
                            'value' => date('Y-m-d'),
                            'template' => '{addon}{input}',
                            'clientOptions' => [
                                'autoclose' => true,
                                'format' => 'yyyy-mm-dd'
                            ]
                        ]); ?>

                    </div>
                    <div class="col-md-6">
                        <label class="control-label" for="to">ถึง</label>
                        <?= \dosamigos\datepicker\DatePicker::widget([
                            'name' => 'to',
                            'value' => date('Y-m-d'),
                            'id' => 'to',
                            'template' => '{addon}{input}',
                            'clientOptions' => [
                                'autoclose' => true,
                                'format' => 'yyyy-mm-dd'
                            ]
                        ]); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" align="center">
                        <br/>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary w-md m-b-5" onclick="download('list-report')">
                    <i class="fas fa-file-excel"></i> Excel
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">ปิด</button>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>